#!/bin/sh

# test for building each example.
for dir in `find examples/* -maxdepth 0 -type d`; do
  cd $dir
  rm -rf .zig-cache
  zframe update
  zig build run
  if [ $? -eq 0 ]; then
    echo -e "\x1B[1;92m($dir) build success.\x1B[m"
  else
    echo -e "\x1B[1;91m($dir) build failed.\x1B[m"
  fi
  cd ../.. # back to project-root
done
