#!/bin/sh

# test for building zframe.
zig build
  if [ $? -eq 0 ]; then
    echo -e "\x1B[1;92m(zframe) build success.\x1B[m"
  else
    echo -e "\x1B[1;91m(zframe) build failed.\x1B[m"
    exit 1
  fi

