#!/bin/sh

# execute all tests
zig build test
  if [ $? -eq 0 ]; then
    echo -e "\x1B[1;92m(zframe) test success.\x1B[m"
  else
    echo -e "\x1B[1;91m(zframe) test failed.\x1B[m"
    exit 1
  fi

# test for building zframe.
zig build
  if [ $? -eq 0 ]; then
    echo -e "\x1B[1;92m(zframe) build success.\x1B[m"
  else
    echo -e "\x1B[1;91m(zframe) build failed.\x1B[m"
    exit 1
  fi

# test for building each test/*.
for dir in `find examples/* -maxdepth 0 -type d`; do
  cd $dir
  rm -rf .zig-cache
  zig build run
  if [ $? -eq 0 ]; then
    echo -e "\x1B[1;92m($dir) build success.\x1B[m"
  else
    echo -e "\x1B[1;91m($dir) build failed.\x1B[m"
    exit 1
  fi
  cd ../.. # back to project-root
done
